### PRUEBA DE REGISTRO

POST http://localhost:8080/register
Content-Type: application/json

{
  "username": "felipe",
  "password": "123"
}

### PRUEBA DE LOGIN

POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "felipe",
  "password": "123"
}

###

